package edu.kit.mensameet.client.model;

public enum MealLines {
    LINE_ONE, LINE_TWO, LINE_THREE, LINE_FOUR_FIVE, CUTLET_BAR, LINE_SIX, LATE_LINE, CURRY_LINE, CAFETERIA, CAFETERIA_LATE, PIZZA_LINE, PIZZA_LINE_PASTA, PIZZA_LINE_SALAD;
}
